name: Test Java

on:
    push:
        branches: ["github-actions"]
    pull_request:
        branches: ["github-actions"]

jobs:
    create-environment:
        uses: ./.github/workflows/createJavaEnv.yml
    build:
        runs-on: ubuntu-latest
        needs: create-environment
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build with Maven
              run: mvn clean package
    test:
        runs-on: ubuntu-latest
        needs: create-environment
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Test with Maven
              run: mvn test
