name: Test Java

on:
  push:
    branches: [ "github-actions" ]
  pull_request:
    branches: [ "github-actions" ]

jobs:
  create-environment:
    uses: ./.github/workflows/createJavaEnv.yml
  build:
    runs-on: ubuntu-latest
    needs: create-environment
    steps:
      - name: Build with Maven
        run: mvn clean package
  test:
    runs-on: ubuntu-latest
    needs: create-environment
    steps:
      - name: Test with Maven
        run: mvn test
