name: Test Java

on:
    push:
        branches: ["github-actions"]
    pull_request:
        branches: ["github-actions"]

jobs:
    create-environment:
        runs-on: ubuntu-latest
        steps: 
          - uses: ./.github/workflows/createJavaEnv.yml
          - uses: actions/checkout@v3
    build:
        runs-on: ubuntu-latest
        needs: create-environment
        steps:
            - name: Build with Maven
              run: mvn clean package
    test:
        runs-on: ubuntu-latest
        needs: create-environment
        steps:
            - name: Test with Maven
              run: mvn test
