name: Test Java

on:
  push:
    branches: [ "github-actions" ]
  pull_request:
    branches: [ "github-actions" ]

jobs:
  create-environment:
    name: Create Java Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

  build:
    runs-on: ubuntu-latest
    steps:
      - needs: create-environment
      - name: Build with Maven
        run: mvn clean package
  test:
    runs-on: ubuntu-latest
    steps:
      - needs: create-environment
      - name: Test with Maven
        run: mvn test
