name: Test Java

on:
  push:
    branches: [ "github-actions" ]
  pull_request:
    branches: [ "github-actions" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean package
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Test with Maven
        run: mvn test
